### ISSUE TITLE
Discussion: Value of asyncWrapper in routes

### ISSUE THREAD

**Issue by smarki** [akoufatzis/nodejs-app-architecture#7]
Looking at the code, it made me question the decision on using asyncWrapper( async () => {}). 
**Problems:** 
- Requires more typing
- Negates the value of async await that is to write vertically readable code
- Adds little of value

**Argument** 
Async await is of value mostly for IO operation that run inlined with sync operations. Allowing the avoidance of cb or promise chain hell. With that said it does seem to add little in this case.

**Comment by akoufatzis** [comment]
It only hides and abstracts away the need to manually call `next(error)` on every route declaration. If you have a route where you don't have any async operation then you clearly don't need the `asyncWrapper` util function but this almost never. At the route definition it provides more readable code because you don't need to wrap every service call in try/catch statements. Further the `asyncWrapper` contains a minimal amount of code and therefore in my opinion it does not hurt the code readability.
